---
language: node_js
node_js:
  - "8.9.1" # N|Solid Version 2.4.1 (Carbon)

notifications:
  email: false

install:
  - cd ./js && npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
